package com.vzw.booking.bg.batch.constants;

/**
 * Error Source Types
 * @author TORELFA
 *
 */
public enum ErrorSource {
	ALTERNATE_BOOKING_INPUT, BILLED_BOOKING_INPUT, UNBILLED_BOOKING_INPUT, ADMIN_FEES_INPUT, BOOK_DATES_INPUT, FINANCIAL_EVENT_OFFSET_INPUT, WHOLESALE_OUTPUT, SUBLEDGER_OUTPUT
}
